"""add indices to foreign keys

Revision ID: 111111111111
Revises: f1583581fded
Create Date: 2026-04-18 17:06:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "111111111111"
down_revision: Union[str, Sequence[str], None] = "f1583581fded"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_movies_user_id"), "movies", ["user_id"], unique=False)
    op.create_index(op.f("ix_movies_tmdb_id"), "movies", ["tmdb_id"], unique=False)
    op.create_index(
        op.f("ix_watched_movies_user_id"), "watched_movies", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_watched_movies_movie_id"), "watched_movies", ["movie_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watched_movies_movie_id"), table_name="watched_movies")
    op.drop_index(op.f("ix_watched_movies_user_id"), table_name="watched_movies")
    op.drop_index(op.f("ix_movies_tmdb_id"), table_name="movies")
    op.drop_index(op.f("ix_movies_user_id"), table_name="movies")
    # ### end Alembic commands ###
