"""add max_toasts column

Revision ID: 2fa377f3ceaa
Revises: a1b2c3d4e5f6
Create Date: 2026-04-18 11:34:27.267322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa377f3ceaa'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('max_toasts', sa.Integer(), server_default='5', nullable=False))
    op.alter_column('watched_movies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watched_movies', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watched_movies', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watched_movies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'max_toasts')
    op.alter_column('movies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
