"""add_poster_url_and_release_date_to_movies

Revision ID: 398019c7597c
Revises: f1583581fded
Create Date: 2026-04-18 18:23:22.541035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398019c7597c'
down_revision: Union[str, Sequence[str], None] = 'f1583581fded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_url', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'release_date')
    op.drop_column('movies', 'poster_url')
    # ### end Alembic commands ###
