"""add constraints and cascade deletes

Revision ID: f1583581fded
Revises: 2fa377f3ceaa
Create Date: 2026-04-18 12:18:33.802543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1583581fded'
down_revision: Union[str, Sequence[str], None] = '2fa377f3ceaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_tmdb_movie', 'movies', ['user_id', 'tmdb_id'])
    op.drop_constraint(op.f('movies_user_id_fkey'), 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_user_watched_movie', 'watched_movies', ['user_id', 'movie_id'])
    op.drop_constraint(op.f('watched_movies_movie_id_fkey'), 'watched_movies', type_='foreignkey')
    op.drop_constraint(op.f('watched_movies_user_id_fkey'), 'watched_movies', type_='foreignkey')
    op.create_foreign_key(None, 'watched_movies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watched_movies', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watched_movies', type_='foreignkey')
    op.drop_constraint(None, 'watched_movies', type_='foreignkey')
    op.create_foreign_key(op.f('watched_movies_user_id_fkey'), 'watched_movies', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('watched_movies_movie_id_fkey'), 'watched_movies', 'movies', ['movie_id'], ['id'])
    op.drop_constraint('uq_user_watched_movie', 'watched_movies', type_='unique')
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key(op.f('movies_user_id_fkey'), 'movies', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_tmdb_movie', 'movies', type_='unique')
    # ### end Alembic commands ###
